---
  - name: install tools
    apt: name={{item}} state=present update_cache=yes
    with_items:
     - python-mysqldb
 
  - name: install mysql-server
    apt: name=mysql-server state=present update_cache=yes

  - name: ensure mysql listening 
    lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf regexp=^bind-address
                line="bind-address = {{ ansible_default_ipv4.address }}"
    notify: restart mysql

  - name: start mysql
    service: name=mysql state=started enabled=yes

  - name: create demo database
    mysql_db: name=demo state=present

  - name: create demo user
    mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present