---
 - hosts: loadbalancers
   become: true
   tasks:
    - name: verify nginx service
      command: service nginx status

- hosts: webserver
  become: true
  tasks:
    - name: verify httpd service
      command: service httpd status

- hosts: database
  become: true
  tasks:
    - name: verify mysql service
      command: service mysql status