---
 - hosts: loadbalancers
   become: true
   tasks:
    - service: name=nginx state=stopped

- hosts: webserver
  become: true
  tasks:
    - service: name=httpd state=stopped

- hosts: database
  become: true
  tasks:
    - service: name=mysql state=restarted

- hosts: webserver
  become: true
  tasks:
    - service: name=httpd state=started

- hosts: loadbalancer
  become: true
  tasks:
    - service: name=nginx state=started
