---
 - hosts: loadbalancers
   become: true
   tasks:
    - name: verify nginx service
      command: service nginx status
    - name: verify nginx is listening on port 80
      wait_for: port=80 timeout=1

 - hosts: webserver
   become: true
   tasks:
    - name: verify httpd service
      command: service httpd status
    - name: verify http is listening on port 80
      wait_for: port=80 timeout=1

 - hosts: database
   become: true
   tasks:
    - name: verify mysql service
      command: service mysql status
    - name: verify mysql is listening on port 80
      wait_for: port=3306 timeout=1