---
 - hosts: webserver
   become: true
   tasks:
    - name: install apache and related stuff
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - httpd
        - python-pip
        - python-virtualenv
        - MySQL-python
        - libsemanage-python
        - epel-release
        - nrpe
        - nagios-plugins*

    - name: start httpd 
      service: name=httpd state=started enabled=yes

    - name: ensure mod_wsgi enabled
      yum:
        name: mod_wsgi
      notify: restart httpd

    - name: copy demo app source
      copy: src=demo/app/ dest=/var/www/demo mode=0755
      notify: restart httpd

    - name: copy apache virtual host config
      copy: src=demo/demo.conf dest=/etc/httpd/conf.d/ mode=0755
      notify: restart httpd

    - name: configure selinux to allow outgoing httpd -> db connections
      seboolean:
        name: httpd_can_network_connect_db
        state: yes
        persistent: yes
      
    - name: ensure nagios client config
      lineinfile: dest=/etc/nagios/nrpe.cfg regexp=^#server_address
                  line="server_address=192.168.55.66"
      notify: restart nagios
    
    - name: start nagios client
      service: name=nrpe state=started enabled=yes
      
    

   handlers:
    - name: restart httpd
      service: name=httpd state=restarted

    - name: restart nagios
      service: name=nrpe state=restarted
    

     
