---
 - hosts: webserver
   become: true
   tasks:
    - name: install apache and related stuff
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - httpd
        - mod_wsgi
        - python-pip
        - python-virtualenv
        - MySQL-python

    - name: start httpd 
      service: name=httpd state=started enabled=yes

    - name: ensure mod_wsgi enabled
      apache2_module: state=present name=mod_wsgi
      notify: restart httpd

   handlers:
    - name: restart httpd
      service: name=httpd state=restarted
    

     
